GET http://localhost:9090/books

HTTP/1.1 200  - OK
content-type: application/json
connection: close
server: ballerina
date: Thu, 12 Feb 2026 16:06:59 +0530
content-encoding: gzip
content-length: 175
###
DELETE http://localhost:9090/books/2

HTTP/1.1 204  - No Content
connection: close
server: ballerina
date: Thu, 12 Feb 2026 15:38:49 +0530
###
PATCH http://localhost:9090/books/3
Content-Type: application/json
{
    "title": "Change title"
}

HTTP/1.1 204  - No Content
connection: close
server: ballerina
date: Thu, 12 Feb 2026 15:42:29 +0530
###
POST http://localhost:9090/books
Content-Type: application/json

{
    "title": "The Hedge Knight",
    "author": "F. Scott Fitzgerald",
    "publishedYear": "1925",
    "genre": "Classic",
    "price": 10.99,
    "quantity": 20
}

HTTP/1.1 201  - Created
content-length: 0
connection: close
server: ballerina
date: Thu, 12 Feb 2026 16:05:29 +0530