GET http://localhost:9090/books
###
GET http://localhost:9090/books/4
###
PATCH http://localhost:9090/books/3
Content-Type: application/json

{
    "title": "Change title"
}
###
POST http://localhost:9090/books
Content-Type: application/json

{
    "title": "The Hedge Knight",
    "author": "F. Scott Fitzgerald",
    "publishedYear": "1925",
    "genre": "Classic",
    "price": 10.99,
    "quantity": 20
}
###
DELETE http://localhost:9090/books/7